# This is a basic workflow to help you get started with Actions

name: Nuget Publish

on:  
  push:
    tags:
      - '*'

jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_KEY: ${{secrets.NUGET_TOKEN}}
      NUGET_FEED: https://api.nuget.org/v3/index.json
      PROJECT_NAME: Gotify.Client
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build -c Release --no-restore
      - name: Create Release NuGet package
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          VERSION="${VERSION//v}"
          dotnet pack -v normal -c Release --include-symbols -p:SymbolPackageFormat=snupkg --include-source -p:PackageVersion=$VERSION -o nupkg src/$PROJECT_NAME/$PROJECT_NAME.*proj
      - name: Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
